# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-11 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0002_auto_20180211_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurerequest',
            name='Product_Area',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Policies'), (1, 'Billing'), (2, 'Claims'), (3, 'Reports')], null=True),
        ),
    ]
